# Generated by Django 5.1.1 on 2025-02-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='Pictures',
            new_name='Picture1',
        ),
        migrations.AddField(
            model_name='complaints',
            name='Picture2',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_pictures/'),
        ),
    ]
