# Generated by Django 5.1.1 on 2025-02-19 22:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_rename_pictures_complaints_picture1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripcontainer',
            name='container',
        ),
        migrations.RemoveField(
            model_name='tripcontainer',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='tripworker',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='tripworker',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='Location',
        ),
        migrations.AddField(
            model_name='waste_container',
            name='Trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_set', to='Staff.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='Distance_km',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='Duration_min',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='Fuel_Spent_Liter',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.DeleteModel(
            name='TripComplaint',
        ),
        migrations.DeleteModel(
            name='TripContainer',
        ),
        migrations.DeleteModel(
            name='TripWorker',
        ),
    ]
