# Generated by Django 5.1.1 on 2025-02-19 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_remove_tripcontainer_container_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landfill',
            name='Latitude_M',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='landfill',
            name='Longitude_M',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='Distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='Duration_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='Fuel_Spent_Liter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='waste_container',
            name='Latitude_M',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='waste_container',
            name='Longitude_M',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.RemoveField(
            model_name='waste_container',
            name='Trip',
        ),
        migrations.AddField(
            model_name='waste_container',
            name='Trip',
            field=models.ManyToManyField(blank=True, null=True, related_name='container_set', to='Staff.trip'),
        ),
    ]
