# Generated by Django 5.1.1 on 2025-05-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_alter_landfill_latitude_m_alter_landfill_longitude_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Deviated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='initial_truck_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='initial_truck_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
    ]
