# Generated by Django 5.1.1 on 2025-05-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0005_trip_deviated_trip_initial_truck_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='Start_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
