# Generated by Django 5.1.1 on 2025-05-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0006_alter_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='request',
            field=models.BooleanField(default=False),
        ),
    ]
