# Generated by Django 5.1.1 on 2025-05-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0007_complaints_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='truck_id',
        ),
        migrations.AddField(
            model_name='complaints',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
