# Generated by Django 5.1.1 on 2025-06-01 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0008_remove_complaints_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=100, unique=True)),
                ('truck_plate', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('workers_name', models.JSONField(default=list)),
                ('start_time', models.DateTimeField()),
                ('Duration_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fuel_spent', models.FloatField(help_text='Fuel spent in liters')),
                ('landfill', models.JSONField(help_text='Landfill info including coordinates')),
                ('start_point', models.JSONField(help_text='Start point coordinates')),
                ('path', models.JSONField(default=list, help_text='List of {timestamp, lat, lon} entries')),
            ],
        ),
    ]
