# Generated by Django 5.1.1 on 2025-06-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0009_historytrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytrip',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historytrip',
            name='fuel_spent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historytrip',
            name='landfill',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historytrip',
            name='path',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='historytrip',
            name='start_point',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historytrip',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historytrip',
            name='truck_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historytrip',
            name='workers_name',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
