# Generated by Django 5.1.1 on 2025-06-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0010_alter_historytrip_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytrip',
            name='container_set',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
