from django.urls import path
from . import views
urlpatterns = [
    path('trucks/',views.TruckList.as_view()),
    path('trucks/<int:id>',views.TruckDetails.as_view()),
    path('location_names/',views.Location_NameList.as_view()),
    path('trips/',views.TripList.as_view()),
    path('trips/<int:id>',views.TripDetails.as_view()),
    path('employees/',views.EmployeeList.as_view()),
    path('employees/<int:id>',views.EmployeeDetails.as_view()),
    path('containers/',views.ContainerList.as_view()),
    path('containers/<int:id>',views.ContainerDetails.as_view()),
    path('landfills/',views.LandfillList.as_view()),
    path('landfills/<int:id>',views.LandfillDetails.as_view()),
    path('complaints/',views.ComplaintList.as_view()),
    path('complaints/<int:id>',views.ComplaintDetails.as_view()),
    path('workers/',views.WorkerList.as_view()),
    path('workers/<int:id>',views.WorkerDetails.as_view()),
    path('drivers/',views.DriverList.as_view()),
    path('drivers/<int:id>',views.DriverDetails.as_view()),
    path('locations/',views.LocationList.as_view()),
    path('locations/<int:id>',views.LocationDetails.as_view()),
    path('user/register/', views.UserRegistrationAPIView.as_view()),
	path('user/login/', views.UserLoginAPIView.as_view()),
	path('user/', views.UserViewAPI.as_view()),
	path('user/logout/', views.UserLogoutViewAPI.as_view()),
    path('users/', views.UserListAPIView.as_view()),
    path('user/<int:user_id>/', views.UserDetailView.as_view()),
    path('upload-image/', views.ImageUploadView.as_view()),
    path('containers/count/', views.WasteContainerCountView.as_view()),
    path('complaints/unsolved/count/', views.UnsolvedComplaintsCountView.as_view()),
    path('complaints/solved/count/', views.SolvedComplaintsCountView.as_view()),
    path('trucks/on_trip/count/', views.OnTripTrucksCountView.as_view()),
    path('trips/fuel-per-month/', views.MonthlyFuelConsumptionView.as_view()),
    path('trips/years/', views.TripsAvailableYearsView.as_view()),
    path('history-trips/', views.HistoryTripList.as_view()),
    path('history-trips/<int:trip_id>/', views.HistoryTripDetails.as_view()),
    path('trips/by-truck/<int:truck_id>/', views.TripsByTruckView.as_view()),
    path('trucks/unassigned/', views.UnassignedTrucksView.as_view()),
]
