# Generated by Django 5.1.1 on 2025-03-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingchange',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
