# Generated by Django 5.1.1 on 2025-05-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_alter_pendingchange_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('manager_user', 'Manager'), ('employee_user', 'Employee')], max_length=20, unique=True)),
                ('table_permissions', models.JSONField(default=dict)),
                ('approval_chain', models.JSONField(default=dict)),
            ],
        ),
    ]
