# Generated by Django 5.1.1 on 2025-05-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_usertypepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingchange',
            name='admin_approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pendingchange',
            name='manager_approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
